"""
Base de données des fonds de teint.
Chaque teinte contient un code hex pour la comparaison colorimétrique.
"""

FOUNDATIONS_DB = {
    "L'Oréal Paris": {
        "True Match (Accord Parfait)": [
            {"ref": "1W", "name": "Porcelaine Dorée",   "hex": "#F5E2C8", "undertone": "warm"},
            {"ref": "1N", "name": "Ivoire",              "hex": "#F3DDCA", "undertone": "neutral"},
            {"ref": "1C", "name": "Rose Porcelaine",     "hex": "#F2DCd0", "undertone": "cool"},
            {"ref": "2W", "name": "Vanille Dorée",       "hex": "#EDD3B0", "undertone": "warm"},
            {"ref": "2N", "name": "Beige Nude",          "hex": "#EBCFAA", "undertone": "neutral"},
            {"ref": "2C", "name": "Rose Vanille",        "hex": "#EDD0B8", "undertone": "cool"},
            {"ref": "3W", "name": "Beige Doré",          "hex": "#E0BC90", "undertone": "warm"},
            {"ref": "3N", "name": "Beige Crème",         "hex": "#DDB888", "undertone": "neutral"},
            {"ref": "3C", "name": "Beige Rosé",          "hex": "#E0B898", "undertone": "cool"},
            {"ref": "4W", "name": "Beige Ambré",         "hex": "#CDA070", "undertone": "warm"},
            {"ref": "4N", "name": "Beige",               "hex": "#C89C6A", "undertone": "neutral"},
            {"ref": "4C", "name": "Beige Rose",          "hex": "#CDA078", "undertone": "cool"},
            {"ref": "5W", "name": "Caramel Doré",        "hex": "#B88050", "undertone": "warm"},
            {"ref": "5N", "name": "Sable",               "hex": "#B07848", "undertone": "neutral"},
            {"ref": "6W", "name": "Moka Doré",           "hex": "#906040", "undertone": "warm"},
            {"ref": "6N", "name": "Ambre",               "hex": "#8C5838", "undertone": "neutral"},
            {"ref": "7W", "name": "Caramel Intense",     "hex": "#7A4830", "undertone": "warm"},
            {"ref": "7N", "name": "Cappuccino",          "hex": "#704030", "undertone": "neutral"},
        ],
        "Infaillible 32H Matte": [
            {"ref": "10",  "name": "Porcelaine",         "hex": "#F5E0CB", "undertone": "neutral"},
            {"ref": "20",  "name": "Ivoire",             "hex": "#F0D9C0", "undertone": "warm"},
            {"ref": "30",  "name": "Sable Rosé",         "hex": "#EDD0B5", "undertone": "cool"},
            {"ref": "100", "name": "Linen",              "hex": "#E8C9A8", "undertone": "warm"},
            {"ref": "110", "name": "Vanilla",            "hex": "#E0C09A", "undertone": "warm"},
            {"ref": "120", "name": "Vanille",            "hex": "#D8B888", "undertone": "neutral"},
            {"ref": "130", "name": "Beige Doré",         "hex": "#CEB070", "undertone": "warm"},
            {"ref": "140", "name": "Beige Ambré",        "hex": "#C0A060", "undertone": "warm"},
            {"ref": "200", "name": "Golden Sand",        "hex": "#B08840", "undertone": "warm"},
            {"ref": "210", "name": "Caramel",            "hex": "#986030", "undertone": "warm"},
            {"ref": "220", "name": "Moka",               "hex": "#7C4828", "undertone": "warm"},
            {"ref": "230", "name": "Espresso",           "hex": "#5C3018", "undertone": "neutral"},
        ],
    },

    "Maybelline": {
        "Fit Me Matte + Poreless": [
            {"ref": "100", "name": "Warm Ivory",         "hex": "#F5E0C0", "undertone": "warm"},
            {"ref": "102", "name": "Fair Ivory",         "hex": "#F2DDB8", "undertone": "warm"},
            {"ref": "105", "name": "Natural Ivory",      "hex": "#EDD5AA", "undertone": "warm"},
            {"ref": "110", "name": "Porcelain",          "hex": "#F0DEC5", "undertone": "neutral"},
            {"ref": "115", "name": "Ivory",              "hex": "#EDD5B0", "undertone": "neutral"},
            {"ref": "120", "name": "Classic Ivory",      "hex": "#E8C898", "undertone": "warm"},
            {"ref": "125", "name": "Nude Beige",         "hex": "#E0C090", "undertone": "neutral"},
            {"ref": "128", "name": "Warm Nude",          "hex": "#DDB880", "undertone": "warm"},
            {"ref": "130", "name": "Buff Beige",         "hex": "#D8B075", "undertone": "warm"},
            {"ref": "220", "name": "Natural Beige",      "hex": "#CEAA6A", "undertone": "neutral"},
            {"ref": "230", "name": "Natural Buff",       "hex": "#C8A060", "undertone": "warm"},
            {"ref": "235", "name": "Pure Beige",         "hex": "#C09858", "undertone": "neutral"},
            {"ref": "240", "name": "Golden Beige",       "hex": "#B89050", "undertone": "warm"},
            {"ref": "310", "name": "Sun Beige",          "hex": "#A87840", "undertone": "warm"},
            {"ref": "320", "name": "Natural Tan",        "hex": "#9C7038", "undertone": "neutral"},
            {"ref": "330", "name": "Toffee",             "hex": "#8C6030", "undertone": "warm"},
            {"ref": "340", "name": "Cappuccino",         "hex": "#7C5028", "undertone": "neutral"},
            {"ref": "355", "name": "Coconut",            "hex": "#6A4020", "undertone": "warm"},
            {"ref": "360", "name": "Espresso",           "hex": "#5A3018", "undertone": "neutral"},
            {"ref": "370", "name": "Toast",              "hex": "#4E2A14", "undertone": "warm"},
            {"ref": "380", "name": "Java",               "hex": "#42200E", "undertone": "neutral"},
        ],
        "SuperStay 24H": [
            {"ref": "10",  "name": "Alabaster",          "hex": "#F8EAE0", "undertone": "neutral"},
            {"ref": "20",  "name": "Cameo",              "hex": "#F3E0CC", "undertone": "cool"},
            {"ref": "21",  "name": "Nude Beige",         "hex": "#EDD5B8", "undertone": "neutral"},
            {"ref": "30",  "name": "Sand",               "hex": "#E8C8A0", "undertone": "warm"},
            {"ref": "40",  "name": "Fawn",               "hex": "#D8B080", "undertone": "warm"},
            {"ref": "48",  "name": "Sun Beige",          "hex": "#C89860", "undertone": "warm"},
            {"ref": "50",  "name": "Warm Caramel",       "hex": "#B88048", "undertone": "warm"},
            {"ref": "58",  "name": "Golden Caramel",     "hex": "#A87038", "undertone": "warm"},
            {"ref": "60",  "name": "Caramel",            "hex": "#986030", "undertone": "neutral"},
            {"ref": "70",  "name": "Cocoa",              "hex": "#7A4828", "undertone": "warm"},
            {"ref": "80",  "name": "Espresso",           "hex": "#5C3218", "undertone": "neutral"},
            {"ref": "85",  "name": "Truffle",            "hex": "#4A2810", "undertone": "warm"},
        ],
    },

    "MAC": {
        "Studio Fix Fluid": [
            {"ref": "NC10",  "name": "NC10",  "hex": "#F7E8D5", "undertone": "warm"},
            {"ref": "NC15",  "name": "NC15",  "hex": "#F2E0C8", "undertone": "warm"},
            {"ref": "NC20",  "name": "NC20",  "hex": "#EDD5B5", "undertone": "warm"},
            {"ref": "NC25",  "name": "NC25",  "hex": "#E8C8A0", "undertone": "warm"},
            {"ref": "NC30",  "name": "NC30",  "hex": "#DDBA88", "undertone": "warm"},
            {"ref": "NC35",  "name": "NC35",  "hex": "#D4AE70", "undertone": "warm"},
            {"ref": "NC40",  "name": "NC40",  "hex": "#C8A058", "undertone": "warm"},
            {"ref": "NC42",  "name": "NC42",  "hex": "#BF9850", "undertone": "warm"},
            {"ref": "NC45",  "name": "NC45",  "hex": "#B09040", "undertone": "warm"},
            {"ref": "NC50",  "name": "NC50",  "hex": "#A08038", "undertone": "warm"},
            {"ref": "NC55",  "name": "NC55",  "hex": "#8C6C2E", "undertone": "warm"},
            {"ref": "NC60",  "name": "NC60",  "hex": "#785A26", "undertone": "warm"},
            {"ref": "NC65",  "name": "NC65",  "hex": "#644820", "undertone": "warm"},
            {"ref": "NW10",  "name": "NW10",  "hex": "#F7E5D8", "undertone": "cool"},
            {"ref": "NW15",  "name": "NW15",  "hex": "#F2DDCE", "undertone": "cool"},
            {"ref": "NW20",  "name": "NW20",  "hex": "#EDD8C5", "undertone": "cool"},
            {"ref": "NW25",  "name": "NW25",  "hex": "#E8D0B8", "undertone": "cool"},
            {"ref": "NW30",  "name": "NW30",  "hex": "#E0C0A0", "undertone": "cool"},
            {"ref": "NW35",  "name": "NW35",  "hex": "#D4A888", "undertone": "cool"},
            {"ref": "NW40",  "name": "NW40",  "hex": "#C89070", "undertone": "cool"},
            {"ref": "NW43",  "name": "NW43",  "hex": "#BC8A60", "undertone": "cool"},
            {"ref": "NW45",  "name": "NW45",  "hex": "#B07850", "undertone": "cool"},
            {"ref": "NW50",  "name": "NW50",  "hex": "#9C6840", "undertone": "cool"},
            {"ref": "NW55",  "name": "NW55",  "hex": "#885830", "undertone": "cool"},
            {"ref": "NW58",  "name": "NW58",  "hex": "#744828", "undertone": "cool"},
            {"ref": "NW60",  "name": "NW60",  "hex": "#643820", "undertone": "cool"},
            {"ref": "NW65",  "name": "NW65",  "hex": "#542E18", "undertone": "cool"},
            {"ref": "NW70",  "name": "NW70",  "hex": "#44240F", "undertone": "cool"},
        ],
        "Pro Longwear": [
            {"ref": "NC15",  "name": "NC15",  "hex": "#F3E0CA", "undertone": "warm"},
            {"ref": "NC20",  "name": "NC20",  "hex": "#EDD5B6", "undertone": "warm"},
            {"ref": "NC30",  "name": "NC30",  "hex": "#DDBA88", "undertone": "warm"},
            {"ref": "NC40",  "name": "NC40",  "hex": "#C9A158", "undertone": "warm"},
            {"ref": "NC45",  "name": "NC45",  "hex": "#B29040", "undertone": "warm"},
            {"ref": "NC50",  "name": "NC50",  "hex": "#A08038", "undertone": "warm"},
            {"ref": "NW20",  "name": "NW20",  "hex": "#EDD8C3", "undertone": "cool"},
            {"ref": "NW30",  "name": "NW30",  "hex": "#E0C09E", "undertone": "cool"},
            {"ref": "NW40",  "name": "NW40",  "hex": "#C8906E", "undertone": "cool"},
            {"ref": "NW50",  "name": "NW50",  "hex": "#9D693E", "undertone": "cool"},
        ],
    },

    "Dior": {
        "Dior Forever": [
            {"ref": "0N",    "name": "Neutre",           "hex": "#F8EAD8", "undertone": "neutral"},
            {"ref": "1N",    "name": "Neutre",           "hex": "#F5E2D0", "undertone": "neutral"},
            {"ref": "1W",    "name": "Warm",             "hex": "#F3DDC0", "undertone": "warm"},
            {"ref": "1CR",   "name": "Cool Rosy",        "hex": "#F5DDD0", "undertone": "cool"},
            {"ref": "2N",    "name": "Neutre",           "hex": "#F0D8C0", "undertone": "neutral"},
            {"ref": "2W",    "name": "Warm",             "hex": "#EDD0B0", "undertone": "warm"},
            {"ref": "2CR",   "name": "Cool Rosy",        "hex": "#F0D5C5", "undertone": "cool"},
            {"ref": "3N",    "name": "Neutre",           "hex": "#E8C8A8", "undertone": "neutral"},
            {"ref": "3W",    "name": "Warm",             "hex": "#E0C090", "undertone": "warm"},
            {"ref": "3CR",   "name": "Cool Rosy",        "hex": "#EAC8B5", "undertone": "cool"},
            {"ref": "4N",    "name": "Neutre",           "hex": "#D8B888", "undertone": "neutral"},
            {"ref": "4W",    "name": "Warm",             "hex": "#D0AE78", "undertone": "warm"},
            {"ref": "4CR",   "name": "Cool Rosy",        "hex": "#D8B8A0", "undertone": "cool"},
            {"ref": "5N",    "name": "Neutre",           "hex": "#C8A870", "undertone": "neutral"},
            {"ref": "5W",    "name": "Warm",             "hex": "#C09858", "undertone": "warm"},
            {"ref": "6N",    "name": "Neutre",           "hex": "#B08848", "undertone": "neutral"},
            {"ref": "6W",    "name": "Warm",             "hex": "#A87838", "undertone": "warm"},
            {"ref": "7N",    "name": "Neutre",           "hex": "#987030", "undertone": "neutral"},
            {"ref": "8N",    "name": "Neutre",           "hex": "#885828", "undertone": "neutral"},
        ],
        "Les Beiges Teint de Santé": [
            {"ref": "10N",   "name": "Très Clair Neutre", "hex": "#F5E5D5", "undertone": "neutral"},
            {"ref": "10W",   "name": "Très Clair Doré",  "hex": "#F3E0C8", "undertone": "warm"},
            {"ref": "20N",   "name": "Clair Neutre",     "hex": "#EDD8C2", "undertone": "neutral"},
            {"ref": "20W",   "name": "Clair Doré",       "hex": "#EAD2B5", "undertone": "warm"},
            {"ref": "30N",   "name": "Moyen Neutre",     "hex": "#E0C5A5", "undertone": "neutral"},
            {"ref": "30W",   "name": "Moyen Doré",       "hex": "#DDB888", "undertone": "warm"},
            {"ref": "40N",   "name": "Moyen-Foncé Neutre","hex": "#CEA870", "undertone": "neutral"},
            {"ref": "40W",   "name": "Moyen-Foncé Doré", "hex": "#C09858", "undertone": "warm"},
            {"ref": "50N",   "name": "Foncé Neutre",     "hex": "#B08848", "undertone": "neutral"},
            {"ref": "60N",   "name": "Très Foncé Neutre","hex": "#906830", "undertone": "neutral"},
        ],
    },

    "Chanel": {
        "Les Beiges": [
            {"ref": "BR12",  "name": "BR12",  "hex": "#F8EAD8", "undertone": "warm"},
            {"ref": "B10",   "name": "B10",   "hex": "#F5E2D5", "undertone": "cool"},
            {"ref": "BR22",  "name": "BR22",  "hex": "#F2DDD0", "undertone": "warm"},
            {"ref": "B20",   "name": "B20",   "hex": "#F0D8C8", "undertone": "cool"},
            {"ref": "BR32",  "name": "BR32",  "hex": "#EDD0C0", "undertone": "warm"},
            {"ref": "B30",   "name": "B30",   "hex": "#EBD0C5", "undertone": "cool"},
            {"ref": "W10",   "name": "W10",   "hex": "#F3DEC8", "undertone": "neutral"},
            {"ref": "W20",   "name": "W20",   "hex": "#EDD5BE", "undertone": "neutral"},
            {"ref": "W30",   "name": "W30",   "hex": "#E5CAAC", "undertone": "neutral"},
            {"ref": "BR42",  "name": "BR42",  "hex": "#D8C0A8", "undertone": "warm"},
            {"ref": "B40",   "name": "B40",   "hex": "#E5C8A5", "undertone": "cool"},
            {"ref": "W40",   "name": "W40",   "hex": "#DEBB95", "undertone": "neutral"},
            {"ref": "BR52",  "name": "BR52",  "hex": "#C8A880", "undertone": "warm"},
            {"ref": "B50",   "name": "B50",   "hex": "#D8B890", "undertone": "cool"},
            {"ref": "W50",   "name": "W50",   "hex": "#D0A87A", "undertone": "neutral"},
            {"ref": "B60",   "name": "B60",   "hex": "#C8A878", "undertone": "cool"},
            {"ref": "W60",   "name": "W60",   "hex": "#BF9668", "undertone": "neutral"},
            {"ref": "B70",   "name": "B70",   "hex": "#B89060", "undertone": "cool"},
            {"ref": "W70",   "name": "W70",   "hex": "#A87E50", "undertone": "neutral"},
            {"ref": "B80",   "name": "B80",   "hex": "#A07848", "undertone": "cool"},
            {"ref": "B90",   "name": "B90",   "hex": "#987038", "undertone": "cool"},
        ],
        "Vitalumière Aqua": [
            {"ref": "10B",   "name": "Beige Pastel",     "hex": "#F3DDD0", "undertone": "cool"},
            {"ref": "20B",   "name": "Beige Clair",      "hex": "#EDD5C8", "undertone": "cool"},
            {"ref": "22B",   "name": "Beige Rosé",       "hex": "#EDD0C8", "undertone": "cool"},
            {"ref": "30B",   "name": "Beige Naturel",    "hex": "#E0C0A8", "undertone": "cool"},
            {"ref": "32B",   "name": "Beige Sable",      "hex": "#DABB98", "undertone": "cool"},
            {"ref": "40B",   "name": "Beige Hâlé",       "hex": "#D0A880", "undertone": "cool"},
            {"ref": "50B",   "name": "Beige Ambré",      "hex": "#BE9060", "undertone": "cool"},
            {"ref": "70B",   "name": "Beige Foncé",      "hex": "#946840", "undertone": "cool"},
        ],
    },

    "Fenty Beauty": {
        "Pro Filt'r Soft Matte Longwear": [
            {"ref": "100W",  "name": "100W",  "hex": "#F7E5D0", "undertone": "warm"},
            {"ref": "110N",  "name": "110N",  "hex": "#F5E2D8", "undertone": "neutral"},
            {"ref": "120C",  "name": "120C",  "hex": "#F3E0D5", "undertone": "cool"},
            {"ref": "130W",  "name": "130W",  "hex": "#EDD5B5", "undertone": "warm"},
            {"ref": "140N",  "name": "140N",  "hex": "#EDD0BC", "undertone": "neutral"},
            {"ref": "150W",  "name": "150W",  "hex": "#E8C8A5", "undertone": "warm"},
            {"ref": "160N",  "name": "160N",  "hex": "#E0C098", "undertone": "neutral"},
            {"ref": "170C",  "name": "170C",  "hex": "#E2C2A8", "undertone": "cool"},
            {"ref": "185W",  "name": "185W",  "hex": "#D8B088", "undertone": "warm"},
            {"ref": "190N",  "name": "190N",  "hex": "#D0A880", "undertone": "neutral"},
            {"ref": "200W",  "name": "200W",  "hex": "#C89860", "undertone": "warm"},
            {"ref": "210N",  "name": "210N",  "hex": "#C09058", "undertone": "neutral"},
            {"ref": "220C",  "name": "220C",  "hex": "#C49070", "undertone": "cool"},
            {"ref": "235W",  "name": "235W",  "hex": "#A87848", "undertone": "warm"},
            {"ref": "245N",  "name": "245N",  "hex": "#A07040", "undertone": "neutral"},
            {"ref": "260W",  "name": "260W",  "hex": "#8C5C30", "undertone": "warm"},
            {"ref": "270N",  "name": "270N",  "hex": "#845828", "undertone": "neutral"},
            {"ref": "280C",  "name": "280C",  "hex": "#886030", "undertone": "cool"},
            {"ref": "395W",  "name": "395W",  "hex": "#6A4020", "undertone": "warm"},
            {"ref": "420N",  "name": "420N",  "hex": "#5A3818", "undertone": "neutral"},
            {"ref": "445C",  "name": "445C",  "hex": "#5C3C20", "undertone": "cool"},
            {"ref": "498N",  "name": "498N",  "hex": "#3A2010", "undertone": "neutral"},
        ],
    },

    "NARS": {
        "Natural Radiant Longwear": [
            {"ref": "Deauville",   "name": "Deauville",   "hex": "#F5E2D5", "undertone": "neutral"},
            {"ref": "Syracuse",    "name": "Syracuse",    "hex": "#F0D8C8", "undertone": "warm"},
            {"ref": "Groenland",   "name": "Groenland",   "hex": "#F0DDD0", "undertone": "cool"},
            {"ref": "Barcelona",   "name": "Barcelona",   "hex": "#E8CDB5", "undertone": "warm"},
            {"ref": "Fiji",        "name": "Fiji",        "hex": "#E8D0C0", "undertone": "neutral"},
            {"ref": "Gobi",        "name": "Gobi",        "hex": "#E5CAB5", "undertone": "cool"},
            {"ref": "Stromboli",   "name": "Stromboli",   "hex": "#E0C0A0", "undertone": "warm"},
            {"ref": "Syracuse II", "name": "Syracuse II", "hex": "#D8B898", "undertone": "neutral"},
            {"ref": "New Guinea",  "name": "New Guinea",  "hex": "#CEAE80", "undertone": "warm"},
            {"ref": "Deauville II","name": "Deauville II","hex": "#C8A078", "undertone": "neutral"},
            {"ref": "Kalahari",    "name": "Kalahari",    "hex": "#C09870", "undertone": "cool"},
            {"ref": "Barcelona II","name": "Barcelona II","hex": "#C09060", "undertone": "warm"},
            {"ref": "Syracuse III","name": "Syracuse III","hex": "#B08040", "undertone": "warm"},
            {"ref": "New Guinea II","name": "New Guinea II","hex": "#A07038","undertone": "neutral"},
            {"ref": "Stromboli II","name": "Stromboli II","hex": "#906030", "undertone": "warm"},
            {"ref": "Syracuse IV", "name": "Syracuse IV", "hex": "#7A4C28", "undertone": "warm"},
            {"ref": "New Guinea III","name": "New Guinea III","hex": "#6C4020","undertone": "neutral"},
            {"ref": "Seychelles",  "name": "Seychelles",  "hex": "#5A3418", "undertone": "neutral"},
        ],
    },

    "Bourjois": {
        "Healthy Mix": [
            {"ref": "51N",   "name": "Vanilla",          "hex": "#F5E0CC", "undertone": "neutral"},
            {"ref": "52W",   "name": "Vanille Clair",    "hex": "#F0D5B8", "undertone": "warm"},
            {"ref": "52.5N", "name": "Beige Clair",      "hex": "#EDD0C0", "undertone": "neutral"},
            {"ref": "53W",   "name": "Beige Clair Doré", "hex": "#E8C8A8", "undertone": "warm"},
            {"ref": "54N",   "name": "Beige",            "hex": "#E0C0A0", "undertone": "neutral"},
            {"ref": "55W",   "name": "Beige Doré",       "hex": "#D8B488", "undertone": "warm"},
            {"ref": "55.5N", "name": "Beige Hâlé",       "hex": "#D0AC80", "undertone": "neutral"},
            {"ref": "56N",   "name": "Beige Foncé",      "hex": "#C8A070", "undertone": "neutral"},
            {"ref": "57W",   "name": "Brun Doré",        "hex": "#B88850", "undertone": "warm"},
            {"ref": "58W",   "name": "Brun Ambré",       "hex": "#A87840", "undertone": "warm"},
            {"ref": "59N",   "name": "Beige Foncé Neutre","hex": "#906030","undertone": "neutral"},
        ],
    },

    "NYX": {
        "Can't Stop Won't Stop": [
            {"ref": "CSWSF01", "name": "Pale",         "hex": "#F8EDE5", "undertone": "neutral"},
            {"ref": "CSWSF02", "name": "Fair",         "hex": "#F5E5D8", "undertone": "warm"},
            {"ref": "CSWSF03", "name": "Light",        "hex": "#F0D8C8", "undertone": "warm"},
            {"ref": "CSWSF04", "name": "Light Ivory",  "hex": "#EEDFCF", "undertone": "neutral"},
            {"ref": "CSWSF05", "name": "Vanilla",      "hex": "#EBDABF", "undertone": "neutral"},
            {"ref": "CSWSF06", "name": "Nude",         "hex": "#E8D0B0", "undertone": "warm"},
            {"ref": "CSWSF08", "name": "True Beige",   "hex": "#E0C4A0", "undertone": "neutral"},
            {"ref": "CSWSF10", "name": "Natural",      "hex": "#D8B890", "undertone": "warm"},
            {"ref": "CSWSF12", "name": "Classic Tan",  "hex": "#C8A078", "undertone": "warm"},
            {"ref": "CSWSF14", "name": "Golden",       "hex": "#BF9460", "undertone": "warm"},
            {"ref": "CSWSF17", "name": "Warm Caramel", "hex": "#A87840", "undertone": "warm"},
            {"ref": "CSWSF19", "name": "Caramel",      "hex": "#9C6E38", "undertone": "warm"},
            {"ref": "CSWSF20", "name": "Espresso",     "hex": "#6C4020", "undertone": "neutral"},
        ],
    },

    "Lancôme": {
        "Teint Idole Ultra Wear": [
            {"ref": "005W",  "name": "Porcelaine",       "hex": "#F8EADA", "undertone": "warm"},
            {"ref": "010N",  "name": "Porcelaine",       "hex": "#F5E0D5", "undertone": "neutral"},
            {"ref": "010W",  "name": "Ivoire",           "hex": "#F3DECC", "undertone": "warm"},
            {"ref": "020N",  "name": "Ivoire",           "hex": "#F0D8CE", "undertone": "neutral"},
            {"ref": "020W",  "name": "Ivoire Doré",      "hex": "#F0D8C0", "undertone": "warm"},
            {"ref": "025N",  "name": "Beige Nude",       "hex": "#EDD0C5", "undertone": "neutral"},
            {"ref": "030W",  "name": "Beige Doré",       "hex": "#EDD0B0", "undertone": "warm"},
            {"ref": "035W",  "name": "Beige Ambré",      "hex": "#E8C8A5", "undertone": "warm"},
            {"ref": "040N",  "name": "Beige Rosé",       "hex": "#E0C5A8", "undertone": "neutral"},
            {"ref": "040W",  "name": "Caramel Doré",     "hex": "#E0BF95", "undertone": "warm"},
            {"ref": "045N",  "name": "Beige Naturel",    "hex": "#D8BA9E", "undertone": "neutral"},
            {"ref": "045W",  "name": "Caramel",          "hex": "#D8B585", "undertone": "warm"},
            {"ref": "050N",  "name": "Beige",            "hex": "#D0B090", "undertone": "neutral"},
            {"ref": "060N",  "name": "Beige Moyen",      "hex": "#C4A07A", "undertone": "neutral"},
            {"ref": "065W",  "name": "Caramel Ambré",    "hex": "#C09560", "undertone": "warm"},
            {"ref": "070N",  "name": "Sable Rosé",       "hex": "#B48A55", "undertone": "neutral"},
            {"ref": "075W",  "name": "Caramel Foncé",    "hex": "#A87B45", "undertone": "warm"},
            {"ref": "080N",  "name": "Tan Foncé",        "hex": "#9C7040", "undertone": "neutral"},
            {"ref": "085W",  "name": "Moka Doré",        "hex": "#8E6235", "undertone": "warm"},
            {"ref": "095W",  "name": "Moka",             "hex": "#7A5028", "undertone": "warm"},
            {"ref": "105W",  "name": "Chocolat",         "hex": "#663D1E", "undertone": "warm"},
            {"ref": "430N",  "name": "Suede Foncé",      "hex": "#583215", "undertone": "neutral"},
            {"ref": "440N",  "name": "Chocolat Intense", "hex": "#4C2A10", "undertone": "neutral"},
        ],
        "Rénergie Lift Armature": [
            {"ref": "005N",  "name": "Ivoire Nacré",     "hex": "#F5E3D8", "undertone": "neutral"},
            {"ref": "010W",  "name": "Ivoire Doré",      "hex": "#F0DDC8", "undertone": "warm"},
            {"ref": "020N",  "name": "Ivoire Rosé",      "hex": "#EDD5CC", "undertone": "neutral"},
            {"ref": "030W",  "name": "Beige Doré",       "hex": "#E8CCB0", "undertone": "warm"},
            {"ref": "040N",  "name": "Beige",            "hex": "#DEC0A5", "undertone": "neutral"},
            {"ref": "050W",  "name": "Caramel Doré",     "hex": "#D0A878", "undertone": "warm"},
            {"ref": "060N",  "name": "Sable",            "hex": "#C09868", "undertone": "neutral"},
        ],
    },
}


# Recommandations blush & rouge à lèvres
# Basées sur : profondeur de teint (L*) + famille de saison (warm/cool/neutral)

MAKEUP_RECO = {
    # Format: (L* min, L* max, saison_famille) -> liste de produits recommandés
    # Famille saison : "warm" = Printemps/Automne, "cool" = Été/Hiver

    "blush": {
        "very_fair_cool":   [  # L* > 72, cool (Été, Hiver)
            {"brand": "Chanel",   "product": "Joues Contraste", "shade": "Romantique",   "hex": "#F2B8C0", "desc": "Rose poudré délicat"},
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Plum Foolery", "hex": "#C87090", "desc": "Rose mauve doux"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "001 Pink",     "hex": "#F0A8B8", "desc": "Rose nacré lumineux"},
            {"brand": "L'Oréal",  "product": "Age Perfect",     "shade": "Rose Nacré",   "hex": "#E8A8B8", "desc": "Rose poudré accessible"},
        ],
        "very_fair_warm":   [  # L* > 72, warm (Printemps, Automne)
            {"brand": "Chanel",   "product": "Joues Contraste", "shade": "Camelia",      "hex": "#F4B098", "desc": "Pêche rosé doux"},
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Peaches",      "hex": "#F0A880", "desc": "Pêche doré iconique"},
            {"brand": "Lancôme",  "product": "Blush Subtil",    "shade": "02 Rose Satin","hex": "#F0B898", "desc": "Pêche rosé lumineux"},
            {"brand": "Maybelline","product": "Fit Me Blush",   "shade": "Light Mauve",  "hex": "#E8A8B0", "desc": "Pêche rosé accessible"},
        ],
        "fair_cool":        [  # L* 62-72, cool
            {"brand": "Chanel",   "product": "Joues Contraste", "shade": "Tendresse",    "hex": "#E890A8", "desc": "Rose vif naturel"},
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Fleur Power",  "hex": "#E08098", "desc": "Rose vif frais"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "004 Coral",    "hex": "#F09080", "desc": "Corail rosé lumineux"},
            {"brand": "L'Oréal",  "product": "True Match Blush","shade": "Rosy Outlook", "hex": "#E09090", "desc": "Rose naturel"},
        ],
        "fair_warm":        [  # L* 62-72, warm
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Warm Soul",    "hex": "#E89070", "desc": "Pêche corail doré"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "005 Coral",    "hex": "#F08870", "desc": "Corail pêche"},
            {"brand": "Lancôme",  "product": "Blush Subtil",    "shade": "Peach Melba",  "hex": "#EE9878", "desc": "Pêche ensoleillé"},
            {"brand": "Maybelline","product": "Fit Me Blush",   "shade": "Peach",        "hex": "#E89880", "desc": "Pêche vif accessible"},
        ],
        "medium_cool":      [  # L* 50-62, cool
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Melba",        "hex": "#D87888", "desc": "Rose foncé lumineux"},
            {"brand": "Chanel",   "product": "Joues Contraste", "shade": "Mystère",      "hex": "#C87088", "desc": "Rose profond"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "006 Berry",    "hex": "#C86880", "desc": "Berry rosé"},
            {"brand": "L'Oréal",  "product": "True Match Blush","shade": "Berry Kiss",   "hex": "#C87888", "desc": "Berry rosé accessible"},
        ],
        "medium_warm":      [  # L* 50-62, warm
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Sunbasque",    "hex": "#D07858", "desc": "Brique terracotta"},
            {"brand": "Lancôme",  "product": "Blush Subtil",    "shade": "Brun Corail",  "hex": "#C87060", "desc": "Corail brique"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "007 Ochre",    "hex": "#C88860", "desc": "Terracotta rosé"},
            {"brand": "Maybelline","product": "Fit Me Blush",   "shade": "Coral",        "hex": "#D07865", "desc": "Corail profond"},
        ],
        "deep_cool":        [  # L* 38-50, cool
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Azalea",       "hex": "#C05870", "desc": "Fuchsia profond"},
            {"brand": "Chanel",   "product": "Joues Contraste", "shade": "Accent",       "hex": "#B85870", "desc": "Bordeaux rosé"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "008 Rosewood", "hex": "#B86070", "desc": "Bois de rose"},
            {"brand": "L'Oréal",  "product": "True Match Blush","shade": "Berry",        "hex": "#B05868", "desc": "Berry profond"},
        ],
        "deep_warm":        [  # L* 38-50, warm
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Burnt Pepper", "hex": "#B06048", "desc": "Terracotta profond"},
            {"brand": "Lancôme",  "product": "Blush Subtil",    "shade": "Cuivre",       "hex": "#B06040", "desc": "Cuivré intense"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "009 Amber",    "hex": "#B07040", "desc": "Ambre doré"},
            {"brand": "Maybelline","product": "Fit Me Blush",   "shade": "Deep Coral",   "hex": "#B06848", "desc": "Brique dorée"},
        ],
        "very_deep_cool":   [  # L* < 38, cool
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Dainty",       "hex": "#A04858", "desc": "Prune rosé"},
            {"brand": "Chanel",   "product": "Joues Contraste", "shade": "Ombre Première","hex": "#985060", "desc": "Prune profond"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "010 Plum",     "hex": "#984858", "desc": "Prune intense"},
            {"brand": "L'Oréal",  "product": "True Match Blush","shade": "Deep Plum",    "hex": "#904858", "desc": "Prune accessible"},
        ],
        "very_deep_warm":   [  # L* < 38, warm
            {"brand": "MAC",      "product": "Powder Blush",    "shade": "Mocha",        "hex": "#985040", "desc": "Moka terracotta"},
            {"brand": "Lancôme",  "product": "Blush Subtil",    "shade": "Brun",         "hex": "#904838", "desc": "Brun chaud profond"},
            {"brand": "Dior",     "product": "Rosy Glow",       "shade": "011 Bronze",   "hex": "#9A5838", "desc": "Bronze brun"},
            {"brand": "Maybelline","product": "Fit Me Blush",   "shade": "Deep Mocha",   "hex": "#905040", "desc": "Moka accessible"},
        ],
    },

    "lipstick": {
        "very_fair_cool":   [
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Pirate",       "hex": "#B82840", "desc": "Rouge framboise classique"},
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Snob",         "hex": "#D87090", "desc": "Rose mauve nude"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "100 Nude Look","hex": "#E8B0A8", "desc": "Nude rosé délicat"},
            {"brand": "L'Oréal",  "product": "Color Riche",  "shade": "Blushing Berry","hex": "#C86080", "desc": "Berry rose lumineux"},
        ],
        "very_fair_warm":   [
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Camelia",      "hex": "#E89080", "desc": "Corail pêche lumineux"},
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Peach Blossom","hex": "#F0A888", "desc": "Pêche rosé doux"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "012 Rosewood", "hex": "#D89080", "desc": "Bois de rose doré"},
            {"brand": "L'Oréal",  "product": "Color Riche",  "shade": "Coral Reef",   "hex": "#E89878", "desc": "Corail nacré"},
        ],
        "fair_cool":        [
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Creme Cup",    "hex": "#E09090", "desc": "Rose nude délicat"},
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Coromandel",   "hex": "#C05070", "desc": "Rose vif profond"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "028 Actrice",  "hex": "#D06888", "desc": "Rose naturel frais"},
            {"brand": "Lancôme",  "product": "L'Absolu Rouge","shade": "Mademoiselle", "hex": "#D07888", "desc": "Rose romantique"},
        ],
        "fair_warm":        [
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Coral Bliss",  "hex": "#E08868", "desc": "Corail chaud vif"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "458 Paname",   "hex": "#D87858", "desc": "Corail mandarine"},
            {"brand": "Lancôme",  "product": "L'Absolu Rouge","shade": "Orange Fizz",  "hex": "#E09070", "desc": "Corail orangé lumineux"},
            {"brand": "L'Oréal",  "product": "Color Riche",  "shade": "Brun Caramel", "hex": "#C08060", "desc": "Nude caramel doré"},
        ],
        "medium_cool":      [
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Brave",        "hex": "#B87878", "desc": "Nude mauve naturel"},
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Audacieuse",   "hex": "#A85870", "desc": "Rose profond frais"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "959 Charnelle","hex": "#C07888", "desc": "Rose brique froid"},
            {"brand": "Lancôme",  "product": "L'Absolu Rouge","shade": "Berry Noir",   "hex": "#A05068", "desc": "Berry profond"},
        ],
        "medium_warm":      [
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Brick-O-La",   "hex": "#B86848", "desc": "Brique terracotta"},
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Ardente",      "hex": "#C07050", "desc": "Rouge brique chaud"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "849 Rouge Cinéma","hex": "#B86050", "desc": "Brique rouge"},
            {"brand": "Lancôme",  "product": "L'Absolu Rouge","shade": "Terre de Mars","hex": "#B06848", "desc": "Terracotta profond"},
        ],
        "deep_cool":        [
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Rebel",        "hex": "#904868", "desc": "Prune profond froid"},
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Magnétique",   "hex": "#883058", "desc": "Bordeaux intense"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "890 Sideral",  "hex": "#804060", "desc": "Mauve profond"},
            {"brand": "Lancôme",  "product": "L'Absolu Rouge","shade": "Berry Rouge",  "hex": "#883858", "desc": "Berry bordeaux"},
        ],
        "deep_warm":        [
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Marrakesh",    "hex": "#904838", "desc": "Brun orangé profond"},
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Cuivreuse",    "hex": "#984038", "desc": "Cuivré intense"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "883 Bold",     "hex": "#983830", "desc": "Brique intense"},
            {"brand": "L'Oréal",  "product": "Color Riche",  "shade": "Amber Rose",   "hex": "#A04838", "desc": "Brun cuivré"},
        ],
        "very_deep_cool":   [
            {"brand": "MAC",      "product": "Lipstick",     "shade": "D for Danger", "hex": "#800030", "desc": "Rouge profond intense"},
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Obscure",      "hex": "#702848", "desc": "Prune très profond"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "969 Poison Metal","hex": "#602040", "desc": "Bordeaux nuit"},
            {"brand": "Lancôme",  "product": "L'Absolu Rouge","shade": "Nuit & Jour",  "hex": "#6A2840", "desc": "Prune nuit"},
        ],
        "very_deep_warm":   [
            {"brand": "MAC",      "product": "Lipstick",     "shade": "Dubonnet",     "hex": "#782830", "desc": "Brun rouge profond"},
            {"brand": "Chanel",   "product": "Rouge Allure", "shade": "Trouble",      "hex": "#802828", "desc": "Rouge brun intense"},
            {"brand": "Dior",     "product": "Rouge Dior",   "shade": "720 Icône",    "hex": "#802020", "desc": "Rouge brique foncé"},
            {"brand": "L'Oréal",  "product": "Color Riche",  "shade": "Chocolate",    "hex": "#703020", "desc": "Chocolat chaud"},
        ],
    },
}
